
name: PullRequest - Diff to Ancestor, Publish and attach Report

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch

  pull_request:
    branches: [ main ]

jobs:
  diff-job2:
    name: Diff to Ancestor, Publish and attach doc report for commenting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
        with:
          command: branch ="${{ github.head_ref }}", diffGitHub_pullrequest(branch)
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: GeneratedArtifacts/DiffReports/

#   Copyright 2022 The MathWorks, Inc.
