
name: Push Request - Diff to Ancestor, Publish and attach Report

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch

  push:
    branches: [ master ]

jobs:
  diff-branches:
    name: Diff new branch to previous commit of the branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Git Diff
        id: diff
        run: |
          latest_commit=$(git rev-parse master);
          prev_commit=$(git rev-parse master~1);
          diffA=$(git diff --name-only --diff-filter=A $latest_commit..$prev_commit -- **/*.slx)
          diffM=$(git diff --name-only --diff-filter=M $latest_commit..$prev_commit -- **/*.slx)
          diffD=$(git diff --name-only --diff-filter=D $latest_commit..$prev_commit -- **/*.slx)
          echo "::set-output name=diffA::$diffA"
          echo "::set-output name=diffM::$diffM"
          echo "::set-output name=diffM::$diffD"
          echo "    Refer to Webview folder to see the new SLX."
          echo "${diffA}"
          echo "    Added SLX files:"
          echo "Deleted SLX files:"
          echo "${diffD}"
          echo "Modified SLX files:"
          echo "${diffM}"

  publish-diff-job:
    needs: diff-branches
    name: Publish and attach doc report for diff'ed SLX files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
        with:
          command: openProject('DCMtrCtrl.prj'); lastpush = "${{ github.event.before }}"; changeList="${{ needs.diff-branches.outputs.diffM }}"; diffGitHub_push(changeList,lastpush)
      - name: Archive Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: push_diffreports
           path: GeneratedArtifacts/DiffReports/

#   Copyright 2022 The MathWorks, Inc.
