# Basic template exmple of setting up CI pipeline with GitHub actions

name: DC Motor Controller Verification

on: 
    # Triggers the workflow only when changes are directly made to the main branch, or when a pull request is made to the main branch
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  
  basic-connectionTest-job:
    name: Simple display command to confirm the pipelines are correctly setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run commands
        uses: matlab-actions/run-command@v1
        with:
          command: disp('MATLAB works on this runner!'); status = license('test','sl_verification_validation')

  my-check-job:
    name: Check Simulink Models for MISRA C Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run commands
        uses: matlab-actions/run-command@v1
        with:
          command: status=license('checkout','sl_verification_validation'); javaVer=version('-java'); if (status~=1 || isempty(javaVer)) disp('No Checks - SlCheck License Missing'); else openProject('DCMtrCtrl.prj'); runProjectChecks; end
      - name: Archive check results
        uses: actions/upload-artifact@v3
        with:
          name: MISRA_C_Checks
          path: GeneratedArtifacts/CheckResults/

  my-test-job:
    name: Test Simulink Models with Simulink test - MiL only
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-pdf: GeneratedArtifacts/TestResults/dcmtr_PIDCtrl_testResults.pdf
          test-results-junit: GeneratedArtifacts/TestResults/dcmtr_PIDCtrl_testResults.xml
          test-results-simulink-test: GeneratedArtifacts/TestResults/dcmtr_PIDCtrl_testResults.mldatx
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Controller Test Results
          path: GeneratedArtifacts/TestResults/
        if: always()
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: GeneratedArtifacts/TestResults/*.xml
        if: always()

  my-codeGen-job:
    name: Generate C Code of Controller Models used in this Project
    if: 1==0                # This  job is intentioanlly getting skipped, as MathWorks does not support transformation processes like code generation on public GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - uses: matlab-actions/run-command@v1
        with:
          command: openProject('DCMtrCtrl.prj'); genCCode;
      - name: Save generated code in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Generated Code
          path: GeneratedArtifacts/WebViews/CodeGen

  my-webview-job:
    name: Generate Webviews of Models used in this Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - uses: matlab-actions/run-command@v1
        with:
          command: openProject('DCMtrCtrl.prj'); genWebView;
      - name: Archive web views
        uses: actions/upload-artifact@v3
        with:
          name: Model Webviews
          path: GeneratedArtifacts/WebViews

  my-webApp-job:
    name: Generate Webapp version of Models used in this Project
    if: 1==0                # This  job is intentioanlly getting skipped, as MathWorks does not support transformation processes like code generation on public GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - uses: matlab-actions/run-command@v1
        with:
          command: openProject('DCMtrCtrl.prj'); genSimpleApp;
      - name: Archive web views
        uses: actions/upload-artifact@v3
        with:
          name: Model Apps
          path: GeneratedArtifacts/DeployableApps